[package]
edition = "2021"
name = "a3-paa"
version = "0.0.1-dev"
description = "Read and write the Bohemia Interactive PAA image format"

[features]
default = ["image"]

[dependencies]
static_assertions = "1.1"
derive_more = "0.99"
byteorder = "1.4"
bstr = "0.2"
segvec = "0.1"
libc = "0.2"
minilzo-rs = "0.6"
log = "0.4"
image = { version = "0.23", optional = true }

[dependencies.bohemia-compression]
git = "https://github.com/IrregularElements/bohemia-compression.git"
rev = "1fd0288507f2868f412f6574c24d80df654ac1bd"

[dev-dependencies]
fern = "0.5"
chrono = "0.4"

[package.metadata]
msrv = "1.56.0"
