[package]
edition = "2021"
name = "a3-paa"
version = "0.0.1-dev"
description = "Read and write the Bohemia Interactive PAA image format"

[features]
default = [ "dxt" ]
dxt = [ "image" ]

[dependencies]
static_assertions = "1.1"
derive_more = "0.99"
byteorder = "1.4"
bstr = "0.2"
segvec = "0.1"
itertools = "0.10"
minilzo-rs = "0.6"
lzss = "0.8"
log = "0.4"
image = { version = "0.23", optional = true }

[dev-dependencies]
fern = "0.5"
chrono = "0.4"
afl = "*"
