[package]
edition = "2021"
name = "a3-paa"
version = "0.0.1-dev"
description = "Read and write the Bohemia Interactive PAA image format"
rust-version = "1.56"

[features]
default = ["encode"]
encode = ["image", "squish"]

[dependencies]
static_assertions = "1.1.0"
derive_more = "0.99.17"
byteorder = "1.4.3"
deku = "0.13.0"
bstr = "0.2.17"
segvec = "0.1.5"
libc = "0.2.117"
minilzo-rs = "0.6.0"
log = "0.4.14"
image = { version = "0.23.14", optional = true }
squish = { version = "2.0.0-beta1", optional = true }

[dependencies.bohemia-compression]
git = "https://github.com/IrregularElements/bohemia-compression.git"
rev = "18cfdedfa530ea4d5468154a1c2210445bd751e2"

[dev-dependencies]
anyhow = { version = "1.0.55", features = ["backtrace"] }
fern = "0.5.9"
chrono = "0.4.19"
clap = { version = "3.1.1", features = ["cargo"] }

[[example]]
name = "paatool"
required-features = ["anyhow/backtrace", "clap/cargo"]
